---

- name: devops.repos
  src: git@git.reform.hmcts.net:devops/repos-role.git
  scm: git
  version: master

- name: devops.common
  src: git@git.reform.hmcts.net:devops/common-role.git
  scm: git
  version: master
